<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LoginApiTest extends TestCase
{
  use RefreshDatabase;
  
  public function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
  
    // 1つのUserインスタンスを作成し、これをテストユーザーにする
    $this->user = factory(User::class)->create();
  }
  
  /**
   * @test
   */
  public function _ログインAPI_登録済みユーザーを認証し返却()
  {
    $response = $this->json('POST', route('login'), [
        'email' => $this->user->email,
        'password' => 'password',
    ]);
    
    // ステータスコードが200であること、nameというjsonデータを持っていることのテスト
    $response
        ->assertStatus(200)
        ->assertJson(['name' => $this->user->name]);
    
    
    // 指定したユーザー($this->user)が認証されていることのテスト
    $this->assertAuthenticatedAs($this->user);
    
  }
}
