<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LogoutApiTest extends TestCase
{
  use RefreshDatabase;
  
  public function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
    
    //ログインの時と同じくテストユーザーの作成
    $this->user = factory(User::class)->create();
  }
  
  /**
   * @test
   */
  public function _ログアウトAPIのテスト()
  {
    //actingAsを使って、テストユーザーを認証状態にしてから、logoutへリクエストをかける
    $response = $this->actingAs($this->user)->json('POST', route('logout'));
    $response->assertStatus(200);
    
    //assertGuestでユーザーが認証されていないことを確認。
    $this->assertGuest();
  }
}
