<?php

namespace Tests\Feature;

use App\Comment;
use App\Content;
use App\Report;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Log;
use Tests\TestCase;

class ReportDestroyApiTest extends TestCase
{
    use RefreshDatabase;
    
    protected function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      
      $this->user = factory(User::class)->create();
    }
    
    /**
     * @test
     */
    public function _日誌の削除()
    {
      Log::debug('日誌の削除APITEST');
  
      $this->withoutExceptionHandling();
  
      factory(Report::class)->create()
          ->each(function ($report) {
        $report->comments()->saveMany(factory(Comment::class, 3)->make());
      });
      $report = Report::first();
      
      $response = $this->actingAs($this->user)
          ->json('DELETE', route('report.destroy', [
              'report_id' => $report->id,
          ]));
  
      Log::debug('response=>assertStatus : '.$response->status());
  
      $response->assertStatus(200);
  
      // DBにレポートが0件登録されていること
      $this->assertEmpty($report);
      $this->assertEquals(0, $report->count());
    }
}
